import traceback


def show_error():
    traceback.print_exc()
